name: CD

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup up Python
              uses:  actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Install build tools
              run: |
                pip install --upgrade pip
                pip install build
            
            - name: Build package
              run: |
                python -m build
            
            - name: Upload ZIP as artifact
              uses:  actions/upload-artifact@v4
              with:
                name: graphqlstore-cli
                path: dist/*.zip
            
            - name: Publish to PyPI
              if: startsWith(github.ref, 'refs/tags/v')
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.PYPI_API_TOKEN }}

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                files: dist/*
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
