name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Setup up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: |
                pip install -r requirements-dev.txt
                pip install -r requirements.txt
                pre-commit install

            - name: Run pre-commit checks
              run: pre-commit run --all-files

            - name: Run tests
              run: pytest
            
            - name: Coverage Report
              id: coverage
              uses: MishaKav/pytest-coverage-comment@main
              with:
                pytest-coverage-path: './reports/coverage.xml'
                junitxml-path: './reports/junit.xml'
                github-token: ${{ secrets.GITHUB_TOKEN }}
              
            - name: Coverage Threshold
              if: ${{ steps.coverage.outputs.coverage < 90 }}
              run: |
                echo "Code coverage is below the threshold of 90%!"
                exit 1
